name: Feature Request
description: For requesting new features
title: "[FR]: "
type: feature
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature
      description: Describe the feature as per outcome it achieves. Solutions should be in a Pull Request supporting the feature outcome.
    validations:
      required: true
  - type: textarea
    id: linked_discussion
    attributes:
      label: Linked discussion
      description: Please link the discussion which has 10 or more upvotes. Invalid input here will mean this Feature Request will be migrated to a discussion for upvoting.
      placeholder: |
        #1234
    validations:
      required: true
